### ISSUE TITLE
[feature required] support multi-arch build

### ISSUE THREAD

**Issue by ozbillwang** [CircleCI-Public/cimg-deploy#24]
Thanks to maintain this image to simplify the docker build. 

But it doesn't support multi-arch build, match to docker command [docker buildx](https://docs.docker.com/build/building/multi-platform/)

Please add the support to multiple platform builds

**Comment by BytesGuy** [comment]
@ozbillwang Hi! Support for arm64 is coming to our docker images soon by way of `buildx`. Work has already begun in the base image here: https://github.com/CircleCI-Public/cimg-base/pull/201 We will eventually roll this out to each image in turn, but we do not currently have an ETA for this. For now, I will tag this issue as a backlog item and once a PR is created to enable this support in this particular repo we will update you. Thanks!

**Comment by BytesGuy** [comment]
Hi, this is closed by https://github.com/CircleCI-Public/cimg-deploy/pull/34 This image supports arm64 from `2023.08.1` onwards
