### ISSUE TITLE
Please, cache this image on public runners

### ISSUE THREAD

**Issue by RomainBillot** [CircleCI-Public/cimg-deploy#5]
This image contains many many tools which takes a lot of spaces.

We only need a few of them, and still, it takes 40s on small instance to download and extract the image, because it is not cached on the runner.

This probably will not be an issue if a lot of people starts using the image, but still, for now it's not really conveniant.

Could you consider either creating separated image (cimg/rsync, cimg/terraforom, ...) or to make these images caches on each runner instance?

Thanks again,

And sorry if it's not the right place to address this.

**Comment by FelicianoTech** [comment]
Hi. Thank you for bringing this up.

So with the way the Docker executor works on CircleCI, the more frequently an image is used, the more likely it will be cached. As this image grows in usage, it should spin up faster for you.

In addition, this image was split out into 3 child images, cimg/aws, cimg/azure, and cimg/gcp. Tools specific to those provides will be put in those images making this one smaller.

I hope that helps.
